name: beer_logging_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3      # Required by your provider code
  path_provider: ^2.1.2  # Required by your provider code
  # Make sure your specific Google Sheets package (like gsheets) is also listed here!

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
