name: Production Compile

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  production_compile:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Repository Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Java Runtime
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Force Purge Old Platform Templates
        run: rm -rf android amdroid ios web windows macos linux

      - name: Regenerate Clean Platform Folders
        run: flutter create --platforms=android .

      - name: Clean Workspace Environment
        run: flutter clean

      - name: Download App Packages
        run: flutter pub get

      - name: Compile Release Binary
        run: flutter build apk --debug

      - name: Export Release Package
        uses: actions/upload-artifact@v4
        with:
          name: beer-inventory-apk
          path: build/app/outputs/apk/debug/app-debug.apk
